<?php

class m131210_144520_soft_deletion extends CDbMigration
{
	public function up()
	{
		$this->addColumn('ophciexamination_anteriorsegment_cct_method','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_anteriorsegment_cct_method_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_anteriorsegment_cortical','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_anteriorsegment_cortical_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_anteriorsegment_nuclear','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_anteriorsegment_nuclear_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_anteriorsegment_pupil','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_anteriorsegment_pupil_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_attribute','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_attribute_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_attribute_element','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_attribute_element_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_attribute_option','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_attribute_option_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_cataractmanagement_eye','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_cataractmanagement_eye_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_cataractmanagement_suitable_for_surgeon','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_cataractmanagement_suitable_for_surgeon_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_clinicoutcome_role','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_clinicoutcome_role_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_clinicoutcome_status','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_clinicoutcome_status_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_clinicoutcome_template','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_clinicoutcome_template_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_comorbidities_assignment','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_comorbidities_assignment_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_comorbidities_item','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_comorbidities_item_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_diagnosis','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_diagnosis_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_dilation_drugs','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_dilation_drugs_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_dilation_treatment','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_dilation_treatment_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_drgrading_clinicalmaculopathy','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_drgrading_clinicalmaculopathy_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_drgrading_clinicalretinopathy','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_drgrading_clinicalretinopathy_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_drgrading_nscmaculopathy','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_drgrading_nscmaculopathy_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_drgrading_nscretinopathy','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_drgrading_nscretinopathy_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_element_set','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_element_set_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_element_set_item','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_element_set_item_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_element_set_rule','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_element_set_rule_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_event_elementset_assignment','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_event_elementset_assignment_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_glaucomarisk_risk','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_glaucomarisk_risk_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_gonioscopy_description','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_gonioscopy_description_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_gonioscopy_van_herick','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_gonioscopy_van_herick_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_injectmanagecomplex_answer','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_injectmanagecomplex_answer_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_injectmanagecomplex_notreatmentreason','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_injectmanagecomplex_notreatmentreason_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_injectmanagecomplex_question','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_injectmanagecomplex_question_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_injectmanagecomplex_risk','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_injectmanagecomplex_risk_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_injectmanagecomplex_risk_assignment','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_injectmanagecomplex_risk_assignment_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_instrument','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_instrument_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_intraocularpressure_reading','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_intraocularpressure_reading_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_lasermanagement_lasertype','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_lasermanagement_lasertype_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_management_deferralreason','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_management_deferralreason_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_management_status','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_management_status_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_oct_fluidstatus','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_oct_fluidstatus_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_oct_fluidtype','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_oct_fluidtype_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_oct_fluidtype_assignment','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_oct_fluidtype_assignment_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_oct_method','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_oct_method_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_opticdisc_cd_ratio','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_opticdisc_cd_ratio_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_opticdisc_lens','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_opticdisc_lens_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_pupillaryabnormalities_abnormality','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_pupillaryabnormalities_abnormality_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_refraction_fraction','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_refraction_fraction_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_refraction_integer','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_refraction_integer_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_refraction_sign','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_refraction_sign_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_refraction_type','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_refraction_type_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_visual_acuity_unit','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_visual_acuity_unit_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_visual_acuity_unit_value','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_visual_acuity_unit_value_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_visualacuity_method','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_visualacuity_method_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_visualacuity_reading','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_visualacuity_reading_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_workflow','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ophciexamination_workflow_version','deleted','tinyint(1) unsigned not null');
	}

	public function down()
	{
		$this->dropColumn('ophciexamination_anteriorsegment_cct_method','deleted');
		$this->dropColumn('ophciexamination_anteriorsegment_cct_method_version','deleted');
		$this->dropColumn('ophciexamination_anteriorsegment_cortical','deleted');
		$this->dropColumn('ophciexamination_anteriorsegment_cortical_version','deleted');
		$this->dropColumn('ophciexamination_anteriorsegment_nuclear','deleted');
		$this->dropColumn('ophciexamination_anteriorsegment_nuclear_version','deleted');
		$this->dropColumn('ophciexamination_anteriorsegment_pupil','deleted');
		$this->dropColumn('ophciexamination_anteriorsegment_pupil_version','deleted');
		$this->dropColumn('ophciexamination_attribute','deleted');
		$this->dropColumn('ophciexamination_attribute_version','deleted');
		$this->dropColumn('ophciexamination_attribute_element','deleted');
		$this->dropColumn('ophciexamination_attribute_element_version','deleted');
		$this->dropColumn('ophciexamination_attribute_option','deleted');
		$this->dropColumn('ophciexamination_attribute_option_version','deleted');
		$this->dropColumn('ophciexamination_cataractmanagement_eye','deleted');
		$this->dropColumn('ophciexamination_cataractmanagement_eye_version','deleted');
		$this->dropColumn('ophciexamination_cataractmanagement_suitable_for_surgeon','deleted');
		$this->dropColumn('ophciexamination_cataractmanagement_suitable_for_surgeon_version','deleted');
		$this->dropColumn('ophciexamination_clinicoutcome_role','deleted');
		$this->dropColumn('ophciexamination_clinicoutcome_role_version','deleted');
		$this->dropColumn('ophciexamination_clinicoutcome_status','deleted');
		$this->dropColumn('ophciexamination_clinicoutcome_status_version','deleted');
		$this->dropColumn('ophciexamination_clinicoutcome_template','deleted');
		$this->dropColumn('ophciexamination_clinicoutcome_template_version','deleted');
		$this->dropColumn('ophciexamination_comorbidities_assignment','deleted');
		$this->dropColumn('ophciexamination_comorbidities_assignment_version','deleted');
		$this->dropColumn('ophciexamination_comorbidities_item','deleted');
		$this->dropColumn('ophciexamination_comorbidities_item_version','deleted');
		$this->dropColumn('ophciexamination_diagnosis','deleted');
		$this->dropColumn('ophciexamination_diagnosis_version','deleted');
		$this->dropColumn('ophciexamination_dilation_drugs','deleted');
		$this->dropColumn('ophciexamination_dilation_drugs_version','deleted');
		$this->dropColumn('ophciexamination_dilation_treatment','deleted');
		$this->dropColumn('ophciexamination_dilation_treatment_version','deleted');
		$this->dropColumn('ophciexamination_drgrading_clinicalmaculopathy','deleted');
		$this->dropColumn('ophciexamination_drgrading_clinicalmaculopathy_version','deleted');
		$this->dropColumn('ophciexamination_drgrading_clinicalretinopathy','deleted');
		$this->dropColumn('ophciexamination_drgrading_clinicalretinopathy_version','deleted');
		$this->dropColumn('ophciexamination_drgrading_nscmaculopathy','deleted');
		$this->dropColumn('ophciexamination_drgrading_nscmaculopathy_version','deleted');
		$this->dropColumn('ophciexamination_drgrading_nscretinopathy','deleted');
		$this->dropColumn('ophciexamination_drgrading_nscretinopathy_version','deleted');
		$this->dropColumn('ophciexamination_element_set','deleted');
		$this->dropColumn('ophciexamination_element_set_version','deleted');
		$this->dropColumn('ophciexamination_element_set_item','deleted');
		$this->dropColumn('ophciexamination_element_set_item_version','deleted');
		$this->dropColumn('ophciexamination_element_set_rule','deleted');
		$this->dropColumn('ophciexamination_element_set_rule_version','deleted');
		$this->dropColumn('ophciexamination_event_elementset_assignment','deleted');
		$this->dropColumn('ophciexamination_event_elementset_assignment_version','deleted');
		$this->dropColumn('ophciexamination_glaucomarisk_risk','deleted');
		$this->dropColumn('ophciexamination_glaucomarisk_risk_version','deleted');
		$this->dropColumn('ophciexamination_gonioscopy_description','deleted');
		$this->dropColumn('ophciexamination_gonioscopy_description_version','deleted');
		$this->dropColumn('ophciexamination_gonioscopy_van_herick','deleted');
		$this->dropColumn('ophciexamination_gonioscopy_van_herick_version','deleted');
		$this->dropColumn('ophciexamination_injectmanagecomplex_answer','deleted');
		$this->dropColumn('ophciexamination_injectmanagecomplex_answer_version','deleted');
		$this->dropColumn('ophciexamination_injectmanagecomplex_notreatmentreason','deleted');
		$this->dropColumn('ophciexamination_injectmanagecomplex_notreatmentreason_version','deleted');
		$this->dropColumn('ophciexamination_injectmanagecomplex_question','deleted');
		$this->dropColumn('ophciexamination_injectmanagecomplex_question_version','deleted');
		$this->dropColumn('ophciexamination_injectmanagecomplex_risk','deleted');
		$this->dropColumn('ophciexamination_injectmanagecomplex_risk_version','deleted');
		$this->dropColumn('ophciexamination_injectmanagecomplex_risk_assignment','deleted');
		$this->dropColumn('ophciexamination_injectmanagecomplex_risk_assignment_version','deleted');
		$this->dropColumn('ophciexamination_instrument','deleted');
		$this->dropColumn('ophciexamination_instrument_version','deleted');
		$this->dropColumn('ophciexamination_intraocularpressure_reading','deleted');
		$this->dropColumn('ophciexamination_intraocularpressure_reading_version','deleted');
		$this->dropColumn('ophciexamination_lasermanagement_lasertype','deleted');
		$this->dropColumn('ophciexamination_lasermanagement_lasertype_version','deleted');
		$this->dropColumn('ophciexamination_management_deferralreason','deleted');
		$this->dropColumn('ophciexamination_management_deferralreason_version','deleted');
		$this->dropColumn('ophciexamination_management_status','deleted');
		$this->dropColumn('ophciexamination_management_status_version','deleted');
		$this->dropColumn('ophciexamination_oct_fluidstatus','deleted');
		$this->dropColumn('ophciexamination_oct_fluidstatus_version','deleted');
		$this->dropColumn('ophciexamination_oct_fluidtype','deleted');
		$this->dropColumn('ophciexamination_oct_fluidtype_version','deleted');
		$this->dropColumn('ophciexamination_oct_fluidtype_assignment','deleted');
		$this->dropColumn('ophciexamination_oct_fluidtype_assignment_version','deleted');
		$this->dropColumn('ophciexamination_oct_method','deleted');
		$this->dropColumn('ophciexamination_oct_method_version','deleted');
		$this->dropColumn('ophciexamination_opticdisc_cd_ratio','deleted');
		$this->dropColumn('ophciexamination_opticdisc_cd_ratio_version','deleted');
		$this->dropColumn('ophciexamination_opticdisc_lens','deleted');
		$this->dropColumn('ophciexamination_opticdisc_lens_version','deleted');
		$this->dropColumn('ophciexamination_pupillaryabnormalities_abnormality','deleted');
		$this->dropColumn('ophciexamination_pupillaryabnormalities_abnormality_version','deleted');
		$this->dropColumn('ophciexamination_refraction_fraction','deleted');
		$this->dropColumn('ophciexamination_refraction_fraction_version','deleted');
		$this->dropColumn('ophciexamination_refraction_integer','deleted');
		$this->dropColumn('ophciexamination_refraction_integer_version','deleted');
		$this->dropColumn('ophciexamination_refraction_sign','deleted');
		$this->dropColumn('ophciexamination_refraction_sign_version','deleted');
		$this->dropColumn('ophciexamination_refraction_type','deleted');
		$this->dropColumn('ophciexamination_refraction_type_version','deleted');
		$this->dropColumn('ophciexamination_visual_acuity_unit','deleted');
		$this->dropColumn('ophciexamination_visual_acuity_unit_version','deleted');
		$this->dropColumn('ophciexamination_visual_acuity_unit_value','deleted');
		$this->dropColumn('ophciexamination_visual_acuity_unit_value_version','deleted');
		$this->dropColumn('ophciexamination_visualacuity_method','deleted');
		$this->dropColumn('ophciexamination_visualacuity_method_version','deleted');
		$this->dropColumn('ophciexamination_visualacuity_reading','deleted');
		$this->dropColumn('ophciexamination_visualacuity_reading_version','deleted');
		$this->dropColumn('ophciexamination_workflow','deleted');
		$this->dropColumn('ophciexamination_workflow_version','deleted');
	}
}
